init spliting .fastq into barcode specific files

diff --git a/subcell b/subcell
--- a/subcell
+++ b/subcell
@@ -53,32 +53,36 @@ sed 's/^.*\(_.*-\).*$/\1/' $input | sed 's/-\|_//g' > "$outfile".tmp
 # Extract reads that belong to the cell barcode
 
 readlink -f $(ls *.fastq.gz) > files.txt
-if [[ $(ls *.fastq.gz | wc -l) == 0 ]]; then
-    echo -e "Directory does not contain the required R1/R2 read files.
-    Please provide the correct directory or make sure .fastq.gz files are compressed"
-else
-    if [[ $(ls *.fastq.gz | grep -E '*_R(1|2)_*' | wc -l) == 0 ]]; then
+count=0
+for i in $(cat "$outfile".tmp); do
+    echo $i > barcode.txt
+    if [[ $(ls *.fastq.gz | wc -l) == 0 ]]; then
         echo -e "Directory does not contain the required R1/R2 read files.
         Please provide the correct directory or make sure .fastq.gz files are compressed"
     else
-        while read l
-        do
-            if ! [[ $(echo $l | grep -E '*_R1_*') == "" ]]; then
-                echo "Processing headers of provided barcodes:"
-                echo $(echo $l | awk -F'[/]' '{print$(NF)}')
-                fqtools find -f "$outfile".tmp "$l" | awk '/^@/ {print $0}' | sed 's/@//g' | sed 's/\ 1:/\ 2:/g' > "$outfile".head
-                wait
-                l2=$(echo $l | sed 's/_R1_/_R2_/g')
-                echo "Processing reads:"
-                echo $(echo $l2 | awk -F'[/]' '{print$(NF)}')
-                filterbyname.sh include=t app=t in="$l2" names="$outfile".head out="$outfile".fastq.gz &> /dev/null
-            fi
-        done < files.txt
-        rm "$outfile".tmp
-        rm "$outfile".head
-	rm files.txt
+        if [[ $(ls *.fastq.gz | grep -E '*_R(1|2)_*' | wc -l) == 0 ]]; then
+            echo -e "Directory does not contain the required R1/R2 read files.
+            Please provide the correct directory or make sure .fastq.gz files are compressed"
+        else
+            while read l
+            do
+                if ! [[ $(echo $l | grep -E '*_R1_*') == "" ]]; then
+                    echo "Processing headers of provided barcodes:"
+                    echo $(echo $l | awk -F'[/]' '{print$(NF)}')
+                    fqtools find -f barcode.txt "$l" | awk '/^@/ {print $0}' | sed 's/@//g' | sed 's/\ 1:/\ 2:/g' >> "$i".head
+                    wait
+                    l2=$(echo $l | sed 's/_R1_/_R2_/g')
+                    echo "Processing reads:"
+                    echo $(echo $l2 | awk -F'[/]' '{print$(NF)}')
+                    filterbyname.sh include=t app=t in="$l2" names="$i".head out="$outfile"_"$count".fastq.gz &> /dev/null
+                fi
+            done < files.txt
+            rm "$outfile".tmp
+            rm "$outfile".head
+        rm files.txt
+        fi
     fi
-fi
+done
 
 # DEACTIVATE CONDA ENVIRONMENT
 conda deactivate &> /dev/null
